apiVersion: v1
kind: Service
metadata:
  name: colyseus
  namespace: codeclashers
spec:
  type: NodePort  # Use NodePort for external access via public IP
  selector:
    app: colyseus
  ports:
  - port: ${COLYSEUS_PORT}
    targetPort: websocket
    nodePort: 30002  # NodePort must be in range 30000-32767
    protocol: TCP

