apiVersion: v1
kind: Service
metadata:
  name: colyseus
  namespace: codeclashers
spec:
  type: LoadBalancer
  selector:
    app: colyseus
  ports:
    - port: 2567
      targetPort: 2567
      protocol: TCP
  loadBalancerIP: ""

