apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: codeclashers
spec:
  type: NodePort  # Use NodePort for external access (Lambda)
  selector:
    app: redis-cluster
  ports:
  - port: ${REDIS_PORT}
    targetPort: 6379
    nodePort: 30000  # External port for Lambda access
    protocol: TCP
    name: client

