apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: codeclashers
data:
  redis.conf: |
    # Redis configuration for persistent password
    appendonly yes
    requirepass ${REDIS_PASSWORD}
    # Save password to config file on startup
    save ""

