apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: codeclashers
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode yes
    dir /data

