apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: codeclashers
data:
  REPLICA_SET_NAME: "rs0"
  REPLICA_COUNT: "3"  # Minimum 3 for proper quorum, must be odd number for voting

