apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codeclashers-dev

resources:
  # RBAC
  - rbac/prometheus-serviceaccount.yaml
  - rbac/prometheus-role.yaml
  - rbac/prometheus-rolebinding.yaml
  - rbac/prometheus-clusterrole.yaml
  - rbac/prometheus-clusterrolebinding.yaml
  - rbac/kube-state-metrics-serviceaccount.yaml
  - rbac/kube-state-metrics-role.yaml
  - rbac/kube-state-metrics-rolebinding.yaml
  
  # ConfigMaps
  - configmaps/prometheus-config.yaml
  - configmaps/grafana-datasource.yaml
  
  # Deployments
  - deployments/prometheus.yaml
  - deployments/grafana.yaml
  - deployments/node-exporter.yaml
  - deployments/kube-state-metrics.yaml
  
  # Services
  - services/prometheus-service.yaml
  - services/grafana-service.yaml
  - services/node-exporter-service.yaml
  - services/kube-state-metrics-service.yaml

