apiVersion: v1
kind: Service
metadata:
  name: colyseus
  namespace: codeclashers-dev
spec:
  type: NodePort
  selector:
    app: colyseus
  ports:
  - port: 2567  # Internal port
    targetPort: 2567
    protocol: TCP
    name: websocket
    nodePort: 30267  # NodePort (accessible via k3d loadbalancer on port 2567)

