# Headless service for Redis Cluster (dev)
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-headless-dev
  namespace: codeclashers-dev
spec:
  clusterIP: None
  selector:
    app: redis-cluster-dev
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip

